import { createHash, randomBytes } from 'node:crypto';
import { getPool } from './db.js';

export async function ensureMerchantPlatform() {
  const db = getPool();
  await db.query(`
    ALTER TABLE merchants ADD COLUMN IF NOT EXISTS logo_url TEXT NULL;
    ALTER TABLE merchants ADD COLUMN IF NOT EXISTS business_address TEXT NULL;
    ALTER TABLE merchants ADD COLUMN IF NOT EXISTS phone VARCHAR(40) NULL;
    ALTER TABLE merchants ADD COLUMN IF NOT EXISTS payment_config JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE merchants ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(30) NOT NULL DEFAULT 'PENDING';
    ALTER TABLE merchants ADD COLUMN IF NOT EXISTS review_reason TEXT NULL;
    CREATE TABLE IF NOT EXISTS merchant_kyc_reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, status VARCHAR(30) NOT NULL, notes TEXT, reviewed_by VARCHAR(320), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS fee_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL, provider VARCHAR(20), percentage NUMERIC(8,4) NOT NULL DEFAULT 0, fixed_amount NUMERIC(18,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS ledger_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, transaction_id UUID NULL REFERENCES transactions(id) ON DELETE SET NULL, type VARCHAR(40) NOT NULL, amount NUMERIC(18,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'BDT', balance_after NUMERIC(18,2) NOT NULL DEFAULT 0, reference VARCHAR(150), metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS ledger_merchant_created_idx ON ledger_entries(merchant_id, created_at DESC);
    CREATE TABLE IF NOT EXISTS settlements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, amount NUMERIC(18,2) NOT NULL, fee NUMERIC(18,2) NOT NULL DEFAULT 0, net_amount NUMERIC(18,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'BDT', status VARCHAR(30) NOT NULL DEFAULT 'PENDING', period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, paid_at TIMESTAMPTZ, reference VARCHAR(150), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS settlements_merchant_created_idx ON settlements(merchant_id, created_at DESC);
    CREATE TABLE IF NOT EXISTS payout_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, amount NUMERIC(18,2) NOT NULL CHECK(amount>0), method VARCHAR(30) NOT NULL, destination TEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', note TEXT, processed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS refunds (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT, merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, amount NUMERIC(18,2) NOT NULL CHECK(amount>0), reason TEXT, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', provider_ref VARCHAR(150), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ);
    CREATE INDEX IF NOT EXISTS refunds_merchant_idx ON refunds(merchant_id, created_at DESC);
    CREATE TABLE IF NOT EXISTS disputes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT, merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, status VARCHAR(30) NOT NULL DEFAULT 'OPEN', reason TEXT, amount NUMERIC(18,2) NOT NULL, evidence JSONB NOT NULL DEFAULT '{}'::jsonb, resolved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS merchant_webhooks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, url TEXT NOT NULL, signing_secret_hash CHAR(64) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, events TEXT[] NOT NULL DEFAULT ARRAY['transaction.*'], created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS webhook_deliveries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), webhook_id UUID NOT NULL REFERENCES merchant_webhooks(id) ON DELETE CASCADE, event_type VARCHAR(100) NOT NULL, payload JSONB NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', attempts INTEGER NOT NULL DEFAULT 0, response_status INTEGER, response_body TEXT, next_attempt_at TIMESTAMPTZ, delivered_at TIMESTAMPTZ, last_error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS webhook_delivery_retry_idx ON webhook_deliveries(status,next_attempt_at);
    CREATE TABLE IF NOT EXISTS merchant_api_keys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE, key_prefix VARCHAR(20) NOT NULL, key_hash CHAR(64) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, last_used_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS admin_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS audit_logs (id BIGSERIAL PRIMARY KEY, actor_type VARCHAR(20) NOT NULL, actor_id VARCHAR(150), action VARCHAR(120) NOT NULL, entity_type VARCHAR(80), entity_id VARCHAR(150), metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS audit_logs_created_idx ON audit_logs(created_at DESC);
  `);
}

const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const secret=()=>`lpwh_${randomBytes(32).toString('hex')}`;
function send(res:any,status:number,data:any){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data));}
function jsonBody(req:any){if(req.body&&typeof req.body==='object')return req.body;try{return JSON.parse(String(req.body||'{}'));}catch{return {};}}
function merchantId(auth:any){return auth?.session?.merchant_id||null;}
async function audit(actorType:string,actorId:string,action:string,entityType?:string,entityId?:string,metadata:any={}){await getPool().query('INSERT INTO audit_logs(actor_type,actor_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[actorType,actorId,action,entityType||null,entityId||null,metadata]);}

export async function handleMerchantPlatform(req:any,res:any,auth:any):Promise<boolean>{
 const path=String(req.url||'').split('?')[0]; const method=String(req.method||'GET').toUpperCase(); const id=merchantId(auth); const db=getPool();
 if(!id)return false;
 if(path==='/api/v1/merchant/business-profile' && method==='GET'){const r=await db.query('SELECT id,name,email,status,logo_url,business_address,phone,payment_config,kyc_status,review_reason,email_verified_at,created_at FROM merchants WHERE id=$1',[id]);return send(res,200,{success:true,data:r.rows[0]})||true;}
 if(path==='/api/v1/merchant/business-profile' && method==='PATCH'){const b=jsonBody(req);const r=await db.query('UPDATE merchants SET name=COALESCE($1,name),logo_url=COALESCE($2,logo_url),business_address=COALESCE($3,business_address),phone=COALESCE($4,phone),payment_config=COALESCE($5,payment_config),updated_at=NOW() WHERE id=$6 RETURNING id,name,email,status,logo_url,business_address,phone,payment_config,kyc_status,review_reason,email_verified_at',[typeof b.name==='string'?b.name.trim():null,typeof b.logoUrl==='string'?b.logoUrl.trim():null,typeof b.address==='string'?b.address.trim():null,typeof b.phone==='string'?b.phone.trim():null,b.paymentConfig&&typeof b.paymentConfig==='object'?b.paymentConfig:null,id]);await audit('MERCHANT',id,'business_profile_updated','merchant',id);return send(res,200,{success:true,data:r.rows[0]})||true;}
 if(path==='/api/v1/merchant/kyc'&&method==='GET'){const r=await db.query('SELECT kyc_status,review_reason FROM merchants WHERE id=$1',[id]);const h=await db.query('SELECT id,status,notes,reviewed_by,created_at FROM merchant_kyc_reviews WHERE merchant_id=$1 ORDER BY created_at DESC',[id]);return send(res,200,{success:true,data:{...r.rows[0],reviews:h.rows}})||true;}
 if(path==='/api/v1/merchant/kyc'&&method==='POST'){const b=jsonBody(req);await db.query("UPDATE merchants SET kyc_status='UNDER_REVIEW',review_reason=$1,updated_at=NOW() WHERE id=$2",[typeof b.notes==='string'?b.notes.slice(0,2000):null,id]);await db.query("INSERT INTO merchant_kyc_reviews(merchant_id,status,notes) VALUES($1,'UNDER_REVIEW',$2)",[id,b.notes||null]);await audit('MERCHANT',id,'kyc_submitted','merchant',id);return send(res,202,{success:true,message:'KYC submitted for review'})||true;}
 if(path==='/api/v1/merchant/balance'&&method==='GET'){const r=await db.query("SELECT COALESCE(SUM(amount) FILTER(WHERE amount>0),0) AS credits,COALESCE(SUM(amount) FILTER(WHERE amount<0),0) AS debits,COALESCE(SUM(amount),0) AS balance FROM ledger_entries WHERE merchant_id=$1",[id]);return send(res,200,{success:true,data:r.rows[0]})||true;}
 if(path==='/api/v1/merchant/ledger'&&method==='GET'){const r=await db.query('SELECT * FROM ledger_entries WHERE merchant_id=$1 ORDER BY created_at DESC LIMIT 200',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/merchant/settlements'&&method==='GET'){const r=await db.query('SELECT * FROM settlements WHERE merchant_id=$1 ORDER BY created_at DESC LIMIT 200',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/merchant/payouts'&&method==='GET'){const r=await db.query('SELECT * FROM payout_requests WHERE merchant_id=$1 ORDER BY created_at DESC LIMIT 200',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/merchant/payouts'&&method==='POST'){const b=jsonBody(req);const amount=Number(b.amount);if(!Number.isFinite(amount)||amount<=0||amount>100000000)return send(res,400,{success:false,message:'Invalid payout amount'})||true;const bal=await db.query('SELECT COALESCE(SUM(amount),0) balance FROM ledger_entries WHERE merchant_id=$1',[id]);if(Number(bal.rows[0].balance)<amount)return send(res,409,{success:false,message:'Insufficient balance'})||true;const r=await db.query('INSERT INTO payout_requests(merchant_id,amount,method,destination) VALUES($1,$2,$3,$4) RETURNING *',[id,amount,String(b.method||'BANK').slice(0,30),String(b.destination||'').slice(0,300)]);await audit('MERCHANT',id,'payout_requested','payout_request',r.rows[0].id);return send(res,201,{success:true,data:r.rows[0]})||true;}
 if(path==='/api/v1/merchant/refunds'&&method==='GET'){const r=await db.query('SELECT * FROM refunds WHERE merchant_id=$1 ORDER BY created_at DESC LIMIT 200',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 const refundMatch=path.match(/^\/api\/v1\/merchant\/transactions\/([^/]+)\/refund$/);if(refundMatch&&method==='POST'){const b=jsonBody(req);const tx=await db.query('SELECT id,amount,status,merchant_id FROM transactions WHERE id=$1 AND merchant_id=$2',[refundMatch[1],id]);if(!tx.rowCount)return send(res,404,{success:false,message:'Transaction not found'})||true;if(tx.rows[0].status!=='SUCCESS')return send(res,409,{success:false,message:'Only successful transactions can be refunded'})||true;const prior=await db.query("SELECT COALESCE(SUM(amount),0) total FROM refunds WHERE transaction_id=$1 AND status NOT IN ('FAILED','CANCELLED')",[refundMatch[1]]);const amount=Math.min(Number(b.amount||tx.rows[0].amount),Number(tx.rows[0].amount)-Number(prior.rows[0].total));if(amount<=0)return send(res,409,{success:false,message:'No refundable amount remains'})||true;const r=await db.query('INSERT INTO refunds(transaction_id,merchant_id,amount,reason) VALUES($1,$2,$3,$4) RETURNING *',[refundMatch[1],id,amount,b.reason||null]);await audit('MERCHANT',id,'refund_requested','refund',r.rows[0].id);return send(res,201,{success:true,data:r.rows[0],message:'Refund queued for provider processing'})||true;}
 if(path==='/api/v1/merchant/webhooks'&&method==='GET'){const r=await db.query('SELECT id,url,active,events,created_at FROM merchant_webhooks WHERE merchant_id=$1 ORDER BY created_at DESC',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/merchant/webhooks'&&method==='POST'){const b=jsonBody(req);const u=String(b.url||'').trim();if(!/^https:\/\//i.test(u))return send(res,400,{success:false,message:'Webhook URL must use HTTPS'})||true;const s=secret();const r=await db.query('INSERT INTO merchant_webhooks(merchant_id,url,signing_secret_hash,events) VALUES($1,$2,$3,$4) RETURNING id,url,active,events,created_at',[id,u,hash(s),Array.isArray(b.events)?b.events.map(String).slice(0,30):['transaction.*']]);await audit('MERCHANT',id,'webhook_created','webhook',r.rows[0].id);return send(res,201,{success:true,data:{...r.rows[0],signingSecret:s}})||true;}
 if(path==='/api/v1/merchant/api-keys'&&method==='GET'){const r=await db.query('SELECT id,key_prefix,name,last_used_at,revoked_at,created_at FROM merchant_api_keys WHERE merchant_id=$1 ORDER BY created_at DESC',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/merchant/api-keys'&&method==='POST'){const b=jsonBody(req);const raw=`lp_live_${randomBytes(32).toString('hex')}`;const r=await db.query('INSERT INTO merchant_api_keys(merchant_id,key_prefix,key_hash,name) VALUES($1,$2,$3,$4) RETURNING id,key_prefix,name,created_at',[id,raw.slice(0,16),hash(raw),String(b.name||'Default API key').slice(0,100)]);await audit('MERCHANT',id,'api_key_created','api_key',r.rows[0].id);return send(res,201,{success:true,data:{...r.rows[0],apiKey:raw}})||true;}
 const revoke=path.match(/^\/api\/v1\/merchant\/api-keys\/([^/]+)$/);if(revoke&&method==='DELETE'){await db.query('UPDATE merchant_api_keys SET revoked_at=NOW() WHERE id=$1 AND merchant_id=$2',[revoke[1],id]);return send(res,200,{success:true})||true;}
 if(path==='/api/v1/merchant/webhook-deliveries'&&method==='GET'){const r=await db.query('SELECT d.* FROM webhook_deliveries d JOIN merchant_webhooks w ON w.id=d.webhook_id WHERE w.merchant_id=$1 ORDER BY d.created_at DESC LIMIT 200',[id]);return send(res,200,{success:true,data:r.rows})||true;}
 return false;
}

export async function handleAdminRoute(req:any,res:any):Promise<boolean>{
 const path=String(req.url||'').split('?')[0];const method=String(req.method||'GET').toUpperCase();const db=getPool();
 if(path==='/api/v1/admin/login'&&method==='POST'){const b=jsonBody(req);const email=String(b.email||'').trim().toLowerCase();const password=String(b.password||'');if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD)return send(res,503,{success:false,message:'Admin authentication is not configured'})||true;if(email!==process.env.ADMIN_EMAIL||password!==process.env.ADMIN_PASSWORD)return send(res,401,{success:false,message:'Invalid admin credentials'})||true;const t=`lpa_${randomBytes(32).toString('hex')}`;await db.query("INSERT INTO admin_sessions(token_hash,expires_at) VALUES($1,NOW()+INTERVAL '8 hours')",[hash(t)]);res.setHeader('Set-Cookie',`lalapay_admin=${t}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`);return send(res,200,{success:true})||true;}
 const cookie=String(req.headers?.cookie||'').split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith('lalapay_admin='))?.slice(14)||'';if(!cookie)return false;const s=await db.query("SELECT id FROM admin_sessions WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>NOW()",[hash(cookie)]);if(!s.rowCount)return false;
 if(path==='/api/v1/admin/logout'&&method==='POST'){await db.query('UPDATE admin_sessions SET revoked_at=NOW() WHERE id=$1',[s.rows[0].id]);res.setHeader('Set-Cookie','lalapay_admin=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');return send(res,200,{success:true})||true;}
 if(path==='/api/v1/admin/merchants'&&method==='GET'){const r=await db.query('SELECT id,name,email,status,kyc_status,created_at FROM merchants ORDER BY created_at DESC LIMIT 500');return send(res,200,{success:true,data:r.rows})||true;}
 const ms=path.match(/^\/api\/v1\/admin\/merchants\/([^/]+)\/(suspend|activate|review)$/);if(ms&&method==='POST'){const status=ms[2]==='suspend'?'SUSPENDED':ms[2]==='activate'?'ACTIVE':'REVIEW';await db.query('UPDATE merchants SET status=$1,updated_at=NOW() WHERE id=$2',[status,ms[1]]);if(ms[2]==='review')await db.query("UPDATE merchants SET kyc_status='UNDER_REVIEW' WHERE id=$1",[ms[1]]);await audit('ADMIN',String(s.rows[0].id),`merchant_${ms[2]}`,'merchant',ms[1]);return send(res,200,{success:true,status})||true;}
 if(path==='/api/v1/admin/transactions'&&method==='GET'){const r=await db.query('SELECT t.*,m.name merchant_name,m.email merchant_email FROM transactions t LEFT JOIN merchants m ON m.id=t.merchant_id ORDER BY t.created_at DESC LIMIT 500');return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/admin/payment-links'&&method==='GET'){const r=await db.query('SELECT p.*,m.name merchant_name FROM payment_links p LEFT JOIN merchants m ON m.id=p.merchant_id ORDER BY p.created_at DESC LIMIT 500');return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/admin/refunds'&&method==='GET'){const r=await db.query('SELECT r.*,m.name merchant_name FROM refunds r JOIN merchants m ON m.id=r.merchant_id ORDER BY r.created_at DESC LIMIT 500');return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/admin/settlements'&&method==='GET'){const r=await db.query('SELECT s.*,m.name merchant_name FROM settlements s JOIN merchants m ON m.id=s.merchant_id ORDER BY s.created_at DESC LIMIT 500');return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/admin/audit-logs'&&method==='GET'){const r=await db.query('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 500');return send(res,200,{success:true,data:r.rows})||true;}
 if(path==='/api/v1/admin/health'&&method==='GET'){const r=await db.query('SELECT (SELECT count(*) FROM merchants) merchants,(SELECT count(*) FROM transactions) transactions,(SELECT count(*) FROM transactions WHERE status IN (\'INITIATED\',\'PENDING\')) pending_transactions,(SELECT count(*) FROM webhook_deliveries WHERE status=\'FAILED\') failed_webhooks');return send(res,200,{success:true,data:r.rows[0]})||true;}
 return false;
}
