import { randomBytes } from 'node:crypto';
import { app } from '../src/server.js';
import { ensureDatabase, getPool, pingDatabase } from '../src/db.js';
import { clearCsrfCookie, clearSessionCookie, createAuthToken, createPasswordHash, csrfCookie, getCookie, randomToken, sessionCookie, sha256, verifyAuthToken, verifyPassword, SESSION_COOKIE, CSRF_COOKIE } from '../src/auth.js';

const SESSION_MAX_AGE = 60 * 60 * 24 * 7;
function json(response: any, status: number, body: unknown, headers: Record<string,string> = {}) { response.statusCode=status; response.setHeader('Content-Type','application/json; charset=utf-8'); for (const [k,v] of Object.entries(headers)) response.setHeader(k,v); response.end(JSON.stringify(body)); }
function body(request: any) { if (!request.body) return {}; if (typeof request.body === 'object') return request.body; try { return JSON.parse(Buffer.isBuffer(request.body) ? request.body.toString('utf8') : String(request.body)); } catch { return {}; } }
function rid(request:any) { const value=String(request.headers?.['x-request-id']??'').trim(); return /^[A-Za-z0-9._:-]{8,100}$/.test(value)?value:randomBytes(12).toString('hex'); }
function ip(request:any) { return String(request.headers?.['x-forwarded-for']??'').split(',')[0]?.trim() || String(request.socket?.remoteAddress??'unknown').slice(0,80); }
function cookies(response:any, values:string[]) { const current=response.getHeader('Set-Cookie'); const existing=Array.isArray(current)?current.map(String):current?[String(current)]:[]; response.setHeader('Set-Cookie',[...existing,...values]); }
async function sendEmail(to:string, subject:string, html:string) { const key=process.env.RESEND_API_KEY; const from=process.env.RESEND_FROM_EMAIL||process.env.FROM_EMAIL; if(!key||!from) return false; const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html})}); return r.ok; }
async function newSession(merchantId:string, token:string) { const csrf=randomToken(32); await getPool().query("INSERT INTO auth_sessions(merchant_id,token_hash,csrf_token,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL '7 days')",[merchantId,sha256(token),csrf]); return csrf; }
async function session(request:any) { const token=getCookie(request,SESSION_COOKIE); if(!token) return null; const auth=verifyAuthToken(token); if(!auth) return null; const method=String(request.method??'GET').toUpperCase(); if(!['GET','HEAD','OPTIONS'].includes(method)){ const c=getCookie(request,CSRF_COOKIE); const h=String(request.headers?.['x-csrf-token']??''); if(!c||c.length!==64||h.length!==64||c!==h) return {invalidCsrf:true}; } const r=await getPool().query(`SELECT s.id,s.merchant_id,s.expires_at,m.status,m.name,m.email,m.email_verified_at FROM auth_sessions s JOIN merchants m ON m.id=s.merchant_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>NOW() LIMIT 1`,[sha256(token)]); if(!r.rowCount||r.rows[0].status!=='ACTIVE') return null; await getPool().query('UPDATE auth_sessions SET last_seen_at=NOW() WHERE id=$1',[r.rows[0].id]); return {token,auth,session:r.rows[0]}; }
async function revokeAll(merchantId:string) { await getPool().query('UPDATE auth_sessions SET revoked_at=NOW() WHERE merchant_id=$1 AND revoked_at IS NULL',[merchantId]); }
async function limit(request:any,key:string,max:number) { await getPool().query('CREATE TABLE IF NOT EXISTS security_rate_limits(key VARCHAR(180) NOT NULL, window_start BIGINT NOT NULL, count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(key,window_start))'); const bucket=Math.floor(Date.now()/60000); const k=`${key}:${ip(request)}`; const r=await getPool().query(`INSERT INTO security_rate_limits(key,window_start,count) VALUES($1,$2,1) ON CONFLICT(key,window_start) DO UPDATE SET count=security_rate_limits.count+1 RETURNING count`,[k,bucket]); return Number(r.rows[0].count)<=max; }
function url(path:string,token:string){const base=process.env.FRONTEND_URL?.replace(/\/$/,'');return base?`${base}${path}?token=${encodeURIComponent(token)}`:null;}
function paymentRouteInfo(request:any){const path=String(request.url??'').split('?')[0];const match=path.match(/^\/api\/v1\/payment-links\/([^/]+)\/pay\/(bkash|nagad)$/);const key=typeof request.headers?.['idempotency-key']==='string'?request.headers['idempotency-key'].trim():'';if(request.method!=='POST'||!match||!key)return null;return{paymentLinkId:match[1],provider:match[2] as 'bkash'|'nagad',key};}

export default async function handler(request:any,response:any){
 let lockClient:any; let released=false; const release=async()=>{if(!lockClient||released)return;released=true;try{await lockClient.query('SELECT pg_advisory_unlock(hashtextextended($1,0))',[paymentRouteInfo(request)?.key??'']);}catch{}try{lockClient.release();}catch{}lockClient=undefined;};
 try{
  await ensureDatabase(); const path=String(request.url??'').split('?')[0]; const requestId=rid(request); response.setHeader('X-Request-ID',requestId); request.headers['x-request-id']=requestId;
  if(path==='/health/ready'){try{await pingDatabase();json(response,200,{status:'ready',service:'lalapay-api'});}catch{json(response,503,{status:'not_ready',service:'lalapay-api',database:false});}return;}
  if(path==='/api/v1/auth/register'&&request.method==='POST'){if(!(await limit(request,'register',8)))return json(response,429,{success:false,message:'Too many requests'});const b=body(request);const name=typeof b.name==='string'?b.name.trim():'';const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';const password=typeof b.password==='string'?b.password:'';if(!name||name.length>150||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||email.length>320||password.length<8||password.length>200)return json(response,400,{success:false,message:'Invalid registration data'});if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32)return json(response,503,{success:false,message:'Authentication is not configured'});const exists=await getPool().query('SELECT id FROM merchants WHERE email=$1 LIMIT 1',[email]);if(exists.rowCount)return json(response,409,{success:false,message:'Email is already registered'});const result=await getPool().query('INSERT INTO merchants(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,status,created_at,email_verified_at',[name,email,await createPasswordHash(password)]);const merchant=result.rows[0];const token=createAuthToken(merchant.id);const csrf=await newSession(merchant.id,token);const verifyToken=randomToken(32);await getPool().query("INSERT INTO auth_tokens(merchant_id,token_hash,purpose,expires_at) VALUES($1,$2,'EMAIL_VERIFICATION',NOW()+INTERVAL '24 hours')",[merchant.id,sha256(verifyToken)]);const verifyLink=url('/verify-email',verifyToken);if(verifyLink){try{await sendEmail(email,'Verify your LalaPay email',`<p>Verify your LalaPay merchant account.</p><p><a href="${verifyLink}">Verify email</a></p>`);}catch{}}cookies(response,[sessionCookie(token,SESSION_MAX_AGE),csrfCookie(csrf,SESSION_MAX_AGE)]);return json(response,201,{success:true,data:{merchant}},{'Cache-Control':'no-store'});}
  if(path==='/api/v1/auth/login'&&request.method==='POST'){if(!(await limit(request,'login',10)))return json(response,429,{success:false,message:'Too many requests'});const b=body(request);const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';const password=typeof b.password==='string'?b.password:'';if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<1||password.length>200)return json(response,400,{success:false,message:'Invalid login data'});const result=await getPool().query('SELECT id,name,email,password_hash,status,created_at,email_verified_at FROM merchants WHERE email=$1 LIMIT 1',[email]);if(!result.rowCount||!(await verifyPassword(password,result.rows[0].password_hash)))return json(response,401,{success:false,message:'Invalid email or password'});const merchant=result.rows[0];if(merchant.status!=='ACTIVE')return json(response,403,{success:false,message:'Merchant account is inactive'});delete merchant.password_hash;const token=createAuthToken(merchant.id);const csrf=await newSession(merchant.id,token);cookies(response,[sessionCookie(token,SESSION_MAX_AGE),csrfCookie(csrf,SESSION_MAX_AGE)]);return json(response,200,{success:true,data:{merchant}},{'Cache-Control':'no-store'});}
  if(path==='/api/v1/auth/logout'&&request.method==='POST'){const s=await session({...request,method:'GET'});if(s&&!(s as any).invalidCsrf)await getPool().query('UPDATE auth_sessions SET revoked_at=NOW() WHERE id=$1',[s.session.id]);cookies(response,[clearSessionCookie(),clearCsrfCookie()]);return json(response,200,{success:true},{'Cache-Control':'no-store'});}
  if(path==='/api/v1/auth/forgot-password'&&request.method==='POST'){if(!(await limit(request,'forgot-password',5)))return json(response,429,{success:false,message:'Too many requests'});const b=body(request);const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||email.length>320)return json(response,400,{success:false,message:'Invalid email'});const r=await getPool().query('SELECT id,email FROM merchants WHERE email=$1 LIMIT 1',[email]);if(r.rowCount){const t=randomToken(32);await getPool().query("INSERT INTO auth_tokens(merchant_id,token_hash,purpose,expires_at) VALUES($1,$2,'PASSWORD_RESET',NOW()+INTERVAL '30 minutes')",[r.rows[0].id,sha256(t)]);const link=url('/reset-password',t);if(link){try{await sendEmail(email,'Reset your LalaPay password',`<p>Your password reset link expires in 30 minutes.</p><p><a href="${link}">Reset password</a></p>`);}catch{}}}return json(response,200,{success:true,message:'If that email exists, a password reset link has been sent.'},{'Cache-Control':'no-store'});}
  if(path==='/api/v1/auth/reset-password'&&request.method==='POST'){if(!(await limit(request,'reset-password',8)))return json(response,429,{success:false,message:'Too many requests'});const b=body(request);const token=typeof b.token==='string'?b.token.trim():'';const password=typeof b.password==='string'?b.password:'';if(!/^[a-f0-9]{64}$/.test(token)||password.length<8||password.length>200)return json(response,400,{success:false,message:'Invalid reset request'});const r=await getPool().query("SELECT id,merchant_id FROM auth_tokens WHERE token_hash=$1 AND purpose='PASSWORD_RESET' AND used_at IS NULL AND expires_at>NOW() LIMIT 1",[sha256(token)]);if(!r.rowCount)return json(response,400,{success:false,message:'Reset link is invalid or expired'});await getPool().query('UPDATE merchants SET password_hash=$1,auth_version=auth_version+1,updated_at=NOW() WHERE id=$2',[await createPasswordHash(password),r.rows[0].merchant_id]);await getPool().query('UPDATE auth_tokens SET used_at=NOW() WHERE id=$1',[r.rows[0].id]);await revokeAll(r.rows[0].merchant_id);return json(response,200,{success:true,message:'Password has been reset. Please log in again.'},{'Cache-Control':'no-store'});}
  if(path==='/api/v1/auth/verify-email'&&request.method==='POST'){if(!(await limit(request,'verify-email',10)))return json(response,429,{success:false,message:'Too many requests'});const b=body(request);const token=typeof b.token==='string'?b.token.trim():'';if(!/^[a-f0-9]{64}$/.test(token))return json(response,400,{success:false,message:'Invalid verification token'});const r=await getPool().query("SELECT id,merchant_id FROM auth_tokens WHERE token_hash=$1 AND purpose='EMAIL_VERIFICATION' AND used_at IS NULL AND expires_at>NOW() LIMIT 1",[sha256(token)]);if(!r.rowCount)return json(response,400,{success:false,message:'Verification link is invalid or expired'});await getPool().query('UPDATE merchants SET email_verified_at=COALESCE(email_verified_at,NOW()),updated_at=NOW() WHERE id=$1',[r.rows[0].merchant_id]);await getPool().query('UPDATE auth_tokens SET used_at=NOW() WHERE id=$1',[r.rows[0].id]);return json(response,200,{success:true,message:'Email verified successfully'},{'Cache-Control':'no-store'});}
  const authSession=await session(request);if(authSession?.invalidCsrf)return json(response,403,{success:false,message:'CSRF validation failed'});if(authSession)request.headers.authorization=`Bearer ${authSession.token}`;
  if(path==='/api/v1/auth/change-password'&&request.method==='POST'){if(!authSession)return json(response,401,{success:false,message:'Authentication required'});if(!(await limit(request,'change-password',5)))return json(response,429,{success:false,message:'Too many requests'});const b=body(request);const current=typeof b.currentPassword==='string'?b.currentPassword:'';const next=typeof b.newPassword==='string'?b.newPassword:'';const r=await getPool().query('SELECT password_hash FROM merchants WHERE id=$1 LIMIT 1',[authSession.session.merchant_id]);if(!r.rowCount||!(await verifyPassword(current,r.rows[0].password_hash)))return json(response,401,{success:false,message:'Current password is incorrect'});if(next.length<8||next.length>200)return json(response,400,{success:false,message:'New password must be 8-200 characters'});await getPool().query('UPDATE merchants SET password_hash=$1,auth_version=auth_version+1,updated_at=NOW() WHERE id=$2',[await createPasswordHash(next),authSession.session.merchant_id]);await revokeAll(authSession.session.merchant_id);const t=createAuthToken(authSession.session.merchant_id);const c=await newSession(authSession.session.merchant_id,t);cookies(response,[sessionCookie(t,SESSION_MAX_AGE),csrfCookie(c,SESSION_MAX_AGE)]);return json(response,200,{success:true,message:'Password changed successfully'},{'Cache-Control':'no-store'});}
  if(path==='/api/v1/merchant/profile'&&(request.method==='GET'||request.method==='PATCH')){if(!authSession)return json(response,401,{success:false,message:'Authentication required'});if(request.method==='GET')return json(response,200,{success:true,data:{id:authSession.session.merchant_id,name:authSession.session.name,email:authSession.session.email,status:authSession.session.status,emailVerified:Boolean(authSession.session.email_verified_at)}});const b=body(request);const name=typeof b.name==='string'?b.name.trim():'';if(!name||name.length>150)return json(response,400,{success:false,message:'Invalid business name'});const r=await getPool().query('UPDATE merchants SET name=$1,updated_at=NOW() WHERE id=$2 RETURNING id,name,email,status,email_verified_at,created_at',[name,authSession.session.merchant_id]);return json(response,200,{success:true,data:r.rows[0]});}
  if(path==='/api/v1/merchant/account'&&request.method==='DELETE'){if(!authSession)return json(response,401,{success:false,message:'Authentication required'});await getPool().query("UPDATE merchants SET status='INACTIVE',auth_version=auth_version+1,updated_at=NOW() WHERE id=$1",[authSession.session.merchant_id]);await revokeAll(authSession.session.merchant_id);cookies(response,[clearSessionCookie(),clearCsrfCookie()]);return json(response,200,{success:true,message:'Merchant account deactivated'});}
  const info=paymentRouteInfo(request);if(info){if(info.key.length<8||info.key.length>150)return json(response,400,{success:false,message:'A valid Idempotency-Key is required'});lockClient=await getPool().connect();await lockClient.query('SELECT pg_advisory_lock(hashtextextended($1,0))',[info.key]);const existing=await lockClient.query(`SELECT t.id,t.provider,t.provider_payment_id,t.provider_redirect_url,t.status FROM transactions t JOIN payment_links pl ON pl.id=t.payment_link_id WHERE pl.merchant_id=(SELECT merchant_id FROM payment_links WHERE public_id=$1 LIMIT 1) AND t.idempotency_key=$2 ORDER BY t.created_at ASC LIMIT 1`,[info.paymentLinkId,info.key]);if(existing.rowCount){const tx=existing.rows[0];await release();if(tx.provider!==info.provider)return json(response,409,{success:false,message:'Idempotency-Key is already bound to another provider',transactionId:tx.id});return json(response,200,{success:true,data:{transactionId:tx.id,paymentId:tx.provider_payment_id,redirectUrl:tx.provider_redirect_url,provider:tx.provider,status:tx.status},reused:true});}response.once('finish',release);response.once('close',release);}
  await app.ready();app.server.emit('request',request,response);
 }catch{await release();if(!response.headersSent)json(response,500,{success:false,message:'Internal server error'});}
}
